braintree_settings.admin_settings_form:  
  path: '/admin/settings/sm_registration'  
  defaults:  
    _form: '\Drupal\braintree_settings\Form\settingsForm'  
    _title: 'Site Configuration'  
  requirements:  
    _permission: 'access administration pages'  
  options:  
    _admin_route: TRUE
braintree_settings.settings_controller:
  path: '/braintree_settings'
  defaults:
    _controller: 'Drupal\braintree_settings\Controller\BraintreeSettingsController::showValues'
    _title: 'custom braintreee module'
  requirements: 
    _permission: 'access content'
  